'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.2012
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Agendas.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Backgammon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Backgammon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calendario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property citas_medicas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citas_medicas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Decrypted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Decrypted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Download_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download 5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Encrypted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Encrypted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Error_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Firewall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Firewall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Index() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Index", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Log_Off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Log_Off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minilogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minilogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search_Engine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search_Engine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sync() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sync", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Time___Date() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Time & Date", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista_Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista_Users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista Users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Windows_Calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Windows Calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
